<?php

namespace AppBundle\Repository;

/**
 * PlaylistListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistListRepository extends \Doctrine\ORM\EntityRepository
{
}